// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: broker_external_links.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBrokerExternalLink = `-- name: CreateBrokerExternalLink :one
INSERT INTO broker_external_links (id, broker_id, type, link, created_at)
values (uuid_generate_v4(), $1, $2, $3, $4)
RETURNING id
`

type CreateBrokerExternalLinkParams struct {
	BrokerID  int64      `json:"broker_id"`
	Type      string     `json:"type"`
	Link      string     `json:"link"`
	CreatedAt *time.Time `json:"created_at"`
}

func (q *Queries) CreateBrokerExternalLink(ctx context.Context, arg CreateBrokerExternalLinkParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createBrokerExternalLink,
		arg.BrokerID,
		arg.Type,
		arg.Link,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
