// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: broker_phone.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBrokerPhone = `-- name: CreateBrokerPhone :one
INSERT INTO broker_phone (id, broker_id, type, number, created_at)
values (uuid_generate_v4(), $1, $2, $3, $4)
RETURNING id
`

type CreateBrokerPhoneParams struct {
	BrokerID  int64      `json:"broker_id"`
	Type      string     `json:"type"`
	Number    string     `json:"number"`
	CreatedAt *time.Time `json:"created_at"`
}

func (q *Queries) CreateBrokerPhone(ctx context.Context, arg CreateBrokerPhoneParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createBrokerPhone,
		arg.BrokerID,
		arg.Type,
		arg.Number,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAllBrokerPhonesByBrokerId = `-- name: GetAllBrokerPhonesByBrokerId :many
SELECT id, broker_id, type, number, created_at FROM broker_phone
WHERE broker_phone.broker_id = $1
`

func (q *Queries) GetAllBrokerPhonesByBrokerId(ctx context.Context, brokerID int64) ([]BrokerPhone, error) {
	rows, err := q.db.Query(ctx, getAllBrokerPhonesByBrokerId, brokerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BrokerPhone
	for rows.Next() {
		var i BrokerPhone
		if err := rows.Scan(
			&i.ID,
			&i.BrokerID,
			&i.Type,
			&i.Number,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
