// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: property_photos.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPropertyPhoto = `-- name: CreatePropertyPhoto :one
INSERT INTO property_photo (id, property_id, link, description, created_at)
values (uuid_generate_v4(), $1, $2, $3, $4)
RETURNING id
`

type CreatePropertyPhotoParams struct {
	PropertyID  int64      `json:"property_id"`
	Link        string     `json:"link"`
	Description *string    `json:"description"`
	CreatedAt   *time.Time `json:"created_at"`
}

func (q *Queries) CreatePropertyPhoto(ctx context.Context, arg CreatePropertyPhotoParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPropertyPhoto,
		arg.PropertyID,
		arg.Link,
		arg.Description,
		arg.CreatedAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
